version: '3.3'

services:
  auth-service:
    build: ./auth_service
    ports:
      - "8000:8000"
    expose:
      - '8000'
    environment:
      - DEBUG=1
   

  courses-service:
    build: ./courses_service
    ports:
      - "8001:8001"
    expose:
      - '8001'
    environment:
      - DEBUG=1
      - AUTH_SERVICE_URL=http://auth-service:8000
    depends_on:
      - auth-service